// <auto-generated />
using System;
using Boxinator_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Boxinator_API.Migrations
{
    [DbContext(typeof(BoxinatorDbContext))]
    [Migration("20230317092041_countrySeedData")]
    partial class countrySeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Boxinator_API.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Multiplier")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Multiplier = 0,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 2,
                            Multiplier = 0,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 3,
                            Multiplier = 0,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 4,
                            Multiplier = 0,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 5,
                            Multiplier = 3,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 6,
                            Multiplier = 3,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 7,
                            Multiplier = 3,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 8,
                            Multiplier = 5,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 9,
                            Multiplier = 5,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 10,
                            Multiplier = 6,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 11,
                            Multiplier = 6,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 12,
                            Multiplier = 6,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 13,
                            Multiplier = 8,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 14,
                            Multiplier = 8,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 15,
                            Multiplier = 7,
                            Name = "France"
                        },
                        new
                        {
                            Id = 16,
                            Multiplier = 9,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 17,
                            Multiplier = 10,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 18,
                            Multiplier = 6,
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Id = 19,
                            Multiplier = 7,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 20,
                            Multiplier = 7,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 21,
                            Multiplier = 9,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 22,
                            Multiplier = 12,
                            Name = "Iceland"
                        });
                });

            modelBuilder.Entity("Boxinator_API.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Boxinator_API.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BoxColor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DestinationID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReciverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationID");

                    b.HasIndex("UserId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Boxinator_API.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Boxinator_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Sub")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShipmentStatus", b =>
                {
                    b.Property<int>("ShipmentsId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("ShipmentsId", "StatusId");

                    b.HasIndex("StatusId");

                    b.ToTable("ShipmentStatus");
                });

            modelBuilder.Entity("Boxinator_API.Models.Shipment", b =>
                {
                    b.HasOne("Boxinator_API.Models.Country", "Destination")
                        .WithMany("Shipments")
                        .HasForeignKey("DestinationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boxinator_API.Models.User", "User")
                        .WithMany("Shipments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Boxinator_API.Models.User", b =>
                {
                    b.HasOne("Boxinator_API.Models.Roles", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ShipmentStatus", b =>
                {
                    b.HasOne("Boxinator_API.Models.Shipment", null)
                        .WithMany()
                        .HasForeignKey("ShipmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boxinator_API.Models.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Boxinator_API.Models.Country", b =>
                {
                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("Boxinator_API.Models.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Boxinator_API.Models.User", b =>
                {
                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
