# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Boxinator-api-v2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_4c03f6c527c54a52b8b197df2bcfb5df }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0029ba2aeafb41baab7ea2b021302d22 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: jakobmbi/boxinator:${{ github.sha }}
        

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Boxinator-api-v2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6f8969f474c84038bd69de60f0024377 }}
        images: 'jakobmbi/boxinator:${{ github.sha }}'
