# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Boxinator-api-v2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_ae1aaec64088470d8f7a6bb0b09baabd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_150a806ff4bb4234b88691a9be30c61a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ae1aaec64088470d8f7a6bb0b09baabd }}/jakobmbi/boxinator:${{ github.sha }}
        file: ./Boxinator-API/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Boxinator-api-v2'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d64ad1e0c3144fa9bde46d84ee0d1dc4 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_ae1aaec64088470d8f7a6bb0b09baabd }}/jakobmbi/boxinator:${{ github.sha }}'
